    version: '3.8'

    services:
      angular-frontend:
        build:
          context: ./FrontEnd
          dockerfile: Dockerfile
        ports:
          - "4200:4200" # Map host port 80 to container port 80
        depends_on:
          - dotnet-backend

      dotnet-backend:
        build:
          context: ./BackEnd
          dockerfile: Dockerfile
        ports:
          - "8080:8080" # Map host port 8080 to container port 8080